# Generated by Django 4.2.6 on 2023-10-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commonName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
