# Generated by Django 4.0.4 on 2023-11-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_commonname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='pricePerKilogram',
        ),
    ]
